services:
  - type: static
    name: maanvifronted
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_BACKEND_URL
        value: https://your-backend-url.onrender.com/api

